import { Inter } from "next/font/google";
import "./globals.css";
import PrelineScript from "./components/PrelineScript";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IDK | INTEGRAL DEVELOPMENT KONSULT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <PrelineScript />
      </body>
    </html>
  );
}
